package com.example.Discovery_Rewards.Student;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.util.*;

@Configuration //  a class  can declare one or more @Bean methods
public class StudentConfig {

    @Bean
    CommandLineRunner commandLineRunner(StudentRepository studentRepository) {
        return args -> {
            Student Llewellyn = new Student( // id will automatically be generated by DB
                    "Llewellyn",
                    "llewellynant@hotmail.com",
                    LocalDate.of(1998,01,12)
            );
            Student Mariam = new Student(
                    "Mariam",
                    "mariam123@gmail.com",
                    LocalDate.of(2000,01,12)
            );
            Student Werner = new Student(
                    "werner",
                    "rocketman@gmail.com",
                    LocalDate.of(1980,01,13)
            );
            ArrayList<Student> students = new ArrayList<Student>();
            students.addAll(List.of(Llewellyn,Mariam,Werner));
            studentRepository.saveAll(students); // commits all students to database
        };
    }
}
